#####################
# Branch management #
#####################

# Number of days of inactivity branch before an Issue will be created.
untilCreateIssue: "1d"

# Number of days of inactivity before an Issue and Related branch will be closed and deleted.
untilDeleteBranch: "5d"

# Issues or Pull Requests with these labels will be wait for do some action
needActionLabel: "need-action"

# First action: hold the Branch and Issue as it will be used in the future
onholdLabel: "onhold"

# Second action: create PR by related Branch
createPRLabel: "need-pr"

# Third action: closed this Issue and delete related Branch
deleteBranchLabel: "delete-branch"

# This is a label to identify issue as a branch management
branchManagementLabel: "branch-management"
