# 1. new branch pushed
# 2. no new push on branch for <warning>
# 3. create label with author name and <warningLabel> label
# 4. if do this list of action to wait delete branch
#    - add new <onholdLabel> label
#    - push new commit to branch
# 5. if do this list of action will be closed/delete branch
#    - do nothing until time exceed
#    - close related issue

# create warning issue
warning: 30m

# add label to pr
warningLabel: warning
onholdLabel: wait

# delete if no new message from author
deletion: 1d

# this username will add as a assignee of the warning issue
admin: kamontat
